---
title: "p8105_mtp_cl4043"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

```{r message=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(patchwork)
```

```{r message=FALSE warning=FALSE}
# importing data
dogweight_df = 
  read_excel(
    "./data/dogweights_07sept2020.xlsx", skip = 1
    )
```

# Problem 1

```{r message=FALSE warning=FALSE}
# tidy and cleaning
dogweight_df <- dogweight_df  %>%
  janitor::clean_names()

# convert date into date format
dogweight_df <- dogweight_df %>% 
    mutate(date = as.numeric(date),
           date = convert_to_date(date)
         )

# data entry at 2018/10/22  1810 should be 18 10
# and at 2019/7/23  1803 should be 18 03 
dogweight_df$raisin[which(dogweight_df$date == "2018-10-22")] <- "18 10"
dogweight_df$raisin[which(dogweight_df$date == "2019-07-23")] <- "18 03"

# also, there is a data entry at 2019/8/14  “07 15” should be “17 15” as the weight can not decrease so quickly, so this might be a mistake
dogweight_df$raisin[which(dogweight_df$date == "2019-08-14")] <- "17 15"

#omit note column for the original data
dogweight_no_note <- dogweight_df  %>% 
  select(date,raisin,simone,gagne,std)
dogweight_note <- dogweight_df  %>% 
  select(date,x6) %>% 
  rename("note" = "x6")

write.csv(dogweight_no_note, file = "dogweight_no_note.csv", row.names = F)
write.csv(dogweight_note, file = "dogweight_note.csv", row.names = F)
```

# Problem 2

```{r}
# How many unique dates are included in the dataset?
summary(dogweight_df)

dogweight_df %>% 
  select(date) %>% 
  unique() %>% 
  drop_na() %>% 
  count()
```

There are 204 unique dates in the dataset.

```{r}
# create a well-formatted table

formatted_table <- dogweight_no_note %>% 
  select(date,raisin,simone,gagne) %>% 
  pivot_longer(
     raisin:gagne,
    names_to = "dog",
    values_to = "lbs_oz"
  )  %>% 
  separate(col = "lbs_oz",
                  into = c("lbs","oz"),
                  sep = " ") %>% 
   mutate(lbs = as.numeric(lbs),
          oz = as.numeric(oz),
          weight = lbs + oz/16) %>% #1 lbs = 16 oz
  select(date,dog,weight) 

# average weight and the standard deviation

formatted_table %>% 
  group_by(dog) %>% 
  summarise(n = sum(!is.na(weight)), 
            weight_na = sum(is.na(weight)),
            mean  = round(mean(weight, na.rm = TRUE), digits = 2),
            sd = round(sd(weight, na.rm = TRUE), digits = 2))
```

 